# Generated by Django 6.0.5 on 2026-05-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, help_text="Rate the freelancer's communication."),
        ),
        migrations.AddField(
            model_name='review',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, help_text='Rate the quality of the work delivered.'),
        ),
        migrations.AddField(
            model_name='review',
            name='timeliness_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, help_text="Rate the freelancer's timeliness."),
        ),
    ]
