# Generated by Django 6.0.5 on 2026-05-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether the freelancer has been verified by an admin.'),
        ),
    ]
